package scenario2.builder;

import shared.model.Booking;
import java.time.LocalDateTime;

/**
 * Builder class for constructing immutable/controlled {@link Booking} objects.
 *
 * <p>This class implements the <b>Builder Design Pattern</b> for Scenario 2
 * (Room Booking & Payment Module). It allows the BookingManager, Payment
 * Service, or UI layer (BookingFX) to create a booking in a clean,
 * step-by-step manner without calling a long constructor directly.
 *
 * <p>Typical usage in the booking flow:
 * <ol>
 *     <li>BookingManager calculates deposit + payment status</li>
 *     <li>BookingBuilder assembles:
 *          <ul>
 *              <li>roomId</li>
 *              <li>userId</li>
 *              <li>start/end time</li>
 *              <li>purpose</li>
 *              <li>deposit + payment status</li>
 *          </ul>
 *     </li>
 *     <li>{@code build()} produces a fully constructed {@link Booking}</li>
 * </ol>
 *
 * <p>This pattern improves:
 * <ul>
 *   <li>Code readability</li>
 *   <li>Flexibility when adding new fields</li>
 *   <li>Unit testing (build partial objects)</li>
 *   <li>Prevents inconsistent Booking creation</li>
 * </ul>
 */
public class BookingBuilder {

    private String bookingId;
    private String roomId;
    private String userId;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private String purpose;

    /** Default booking status mirrors Booking defaults ("CONFIRMED"). */
    private String status = "CONFIRMED";

    /** Default payment status mirrors Booking defaults ("PENDING"). */
    private String paymentStatus = "PENDING";

    /** Deposit amount collected at booking time (1×hour rate). */
    private double depositAmount = 0.0;

    // ===============================================================
    //                        FLUENT SETTERS
    // ===============================================================

    /**
     * @param bookingId a unique reservation ID generated by BookingManager
     * @return this builder instance (for chaining)
     */
    public BookingBuilder setBookingId(String bookingId) {
        this.bookingId = bookingId;
        return this;
    }

    /**
     * @param roomId ID of the room being reserved
     * @return this builder instance
     */
    public BookingBuilder setRoomId(String roomId) {
        this.roomId = roomId;
        return this;
    }

    /**
     * @param userId email or ID of the user making the reservation
     * @return this builder instance
     */
    public BookingBuilder setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * @param startTime start date/time of the booking
     * @return this builder instance
     */
    public BookingBuilder setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * @param endTime end date/time of the booking
     * @return this builder instance
     */
    public BookingBuilder setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * @param purpose meeting purpose/description
     * @return this builder instance
     */
    public BookingBuilder setPurpose(String purpose) {
        this.purpose = purpose;
        return this;
    }

    /**
     * Overrides the default booking status ("CONFIRMED").
     * Useful when loading from CSV or marking as "PENDING_PAYMENT".
     *
     * @param status new booking status
     * @return this builder instance
     */
    public BookingBuilder setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Sets the payment status determined by the payment strategy.
     *
     * @param paymentStatus payment result ("PENDING", "APPROVED", "FAILED")
     * @return this builder instance
     */
    public BookingBuilder setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
        return this;
    }

    /**
     * Specifies the deposit charged at booking time.
     *
     * @param depositAmount amount to charge
     * @return this builder instance
     */
    public BookingBuilder setDepositAmount(double depositAmount) {
        this.depositAmount = depositAmount;
        return this;
    }

    // ===============================================================
    //                           BUILD
    // ===============================================================

    /**
     * Builds the final {@link Booking} object.
     *
     * <p>Performs minimal validation to ensure that the Booking created
     * is complete and valid. Missing required fields will throw an error.
     *
     * @return fully constructed Booking instance
     * @throws IllegalStateException if required fields are missing
     */
    public Booking build() {
        // Validate required fields
        if (bookingId == null || roomId == null || userId == null ||
                startTime == null || endTime == null) {

            throw new IllegalStateException(
                    "Booking requires: bookingId, roomId, userId, startTime, and endTime."
            );
        }

        if (purpose == null) {
            purpose = "";
        }

        // Construct using the full Booking constructor
        return new Booking(
                bookingId,
                roomId,
                userId,
                startTime,
                endTime,
                purpose,
                status,
                paymentStatus,
                depositAmount
        );
    }
}
